#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class StackPanel;
                ref class Button;
                ref class ComboBox;
                ref class TextBox;
            }
        }
    }
}

namespace Projekt_v1
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::StackPanel^ contentPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ InputPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ OutputPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ NumbersPanel0;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ NumbersPanel1;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ NumbersPanel2;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ NumbersPanel3;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ NumbersPanel4;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ NumbersPanel5;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ NumbersPanel6;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ ComboBoxPanel1;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ Panel1;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonConv;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ comboBox1;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ comboBox2;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonEqu;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonA;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonB;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonC;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonD;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonE;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonF;
        private: ::Windows::UI::Xaml::Controls::Button^ Button;
        private: ::Windows::UI::Xaml::Controls::Button^ Button0;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonDiv;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonMod;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonBIN;
        private: ::Windows::UI::Xaml::Controls::Button^ Button7;
        private: ::Windows::UI::Xaml::Controls::Button^ Button8;
        private: ::Windows::UI::Xaml::Controls::Button^ Button9;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonMult;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonPow;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonOCT;
        private: ::Windows::UI::Xaml::Controls::Button^ Button4;
        private: ::Windows::UI::Xaml::Controls::Button^ Button5;
        private: ::Windows::UI::Xaml::Controls::Button^ Button6;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonSub;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonRightParan;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonHEX;
        private: ::Windows::UI::Xaml::Controls::Button^ Button1;
        private: ::Windows::UI::Xaml::Controls::Button^ Button2;
        private: ::Windows::UI::Xaml::Controls::Button^ Button3;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonAdd;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonLeftParan;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonClr;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonAns;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Output;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Input;
    };
}

