//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::Projekt_v1::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Projekt_v1::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->contentPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 2:
            {
                this->InputPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 3:
            {
                this->OutputPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 4:
            {
                this->NumbersPanel0 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 5:
            {
                this->NumbersPanel1 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 6:
            {
                this->NumbersPanel2 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 7:
            {
                this->NumbersPanel3 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 8:
            {
                this->NumbersPanel4 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 9:
            {
                this->NumbersPanel5 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 10:
            {
                this->NumbersPanel6 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 11:
            {
                this->ComboBoxPanel1 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 12:
            {
                this->Panel1 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 13:
            {
                this->ButtonConv = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonConv))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonConv_Click);
            }
            break;
        case 14:
            {
                this->comboBox1 = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->comboBox1))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::ComboBox_SelectionChanged1);
            }
            break;
        case 15:
            {
                this->comboBox2 = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->comboBox2))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::ComboBox_SelectionChanged2);
            }
            break;
        case 16:
            {
                this->ButtonEqu = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonEqu))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonEqu_Click);
            }
            break;
        case 17:
            {
                this->ButtonA = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonA))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonA_Click);
            }
            break;
        case 18:
            {
                this->ButtonB = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonB))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonB_Click);
            }
            break;
        case 19:
            {
                this->ButtonC = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonC))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonC_Click);
            }
            break;
        case 20:
            {
                this->ButtonD = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonD))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonD_Click);
            }
            break;
        case 21:
            {
                this->ButtonE = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonE))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonE_Click);
            }
            break;
        case 22:
            {
                this->ButtonF = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonF))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonF_Click);
            }
            break;
        case 23:
            {
                this->Button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 24:
            {
                this->Button0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Button0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button0_Click);
            }
            break;
        case 25:
            {
                this->ButtonDiv = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonDiv))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonDiv_Click);
            }
            break;
        case 26:
            {
                this->ButtonMod = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonMod))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonMod_Click);
            }
            break;
        case 27:
            {
                this->ButtonBIN = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonBIN))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonBIN_Click);
            }
            break;
        case 28:
            {
                this->Button7 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Button7))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button7_Click);
            }
            break;
        case 29:
            {
                this->Button8 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Button8))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button8_Click);
            }
            break;
        case 30:
            {
                this->Button9 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Button9))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button9_Click);
            }
            break;
        case 31:
            {
                this->ButtonMult = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonMult))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonMult_Click);
            }
            break;
        case 32:
            {
                this->ButtonPow = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonPow))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonPow_Click);
            }
            break;
        case 33:
            {
                this->ButtonOCT = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonOCT))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonOCT_Click);
            }
            break;
        case 34:
            {
                this->Button4 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Button4))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button4_Click);
            }
            break;
        case 35:
            {
                this->Button5 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Button5))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button5_Click);
            }
            break;
        case 36:
            {
                this->Button6 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Button6))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button6_Click);
            }
            break;
        case 37:
            {
                this->ButtonSub = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonSub))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonSub_Click);
            }
            break;
        case 38:
            {
                this->ButtonRightParan = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonRightParan))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonRightParan_Click);
            }
            break;
        case 39:
            {
                this->ButtonHEX = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonHEX))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonHEX_Click);
            }
            break;
        case 40:
            {
                this->Button1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Button1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button1_Click);
            }
            break;
        case 41:
            {
                this->Button2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Button2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button2_Click);
            }
            break;
        case 42:
            {
                this->Button3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Button3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button3_Click);
            }
            break;
        case 43:
            {
                this->ButtonAdd = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonAdd))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonAdd_Click);
            }
            break;
        case 44:
            {
                this->ButtonLeftParan = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonLeftParan))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonLeftParan_Click);
            }
            break;
        case 45:
            {
                ::Windows::UI::Xaml::Controls::AppBarButton^ element45 = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(element45))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonCl_Click);
            }
            break;
        case 46:
            {
                this->ButtonClr = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonClr))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonClr_Click);
            }
            break;
        case 47:
            {
                this->ButtonAns = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ButtonAns))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Projekt_v1::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::ButtonAns_Click);
            }
            break;
        case 48:
            {
                this->Output = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 49:
            {
                this->Input = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Projekt_v1::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


